### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/district-builder-2#49]
Endpoints:
* Sign up for account
  * Triggers invitation email
* Uses link in invitation email to complete registration
Models:
* User model(s) 
  * Update existing with fields we need
  * Create new models as necessary (preregistered user?)

AC:
* Send new user payload to registration endpoint
* Email address receives registration email
* Clicking on link in email registers user
* User is now listed on the home page (show that a user has been created)

**Comment by hectcastro** [comment]
A heads up that for the email sending portion of this, we are going to need to identify a Node.js/NestJS specific solution for sending email through Amazon SES with instance metadata provided credentials.

This can be done in a primitive way with the AWS SDK for JavaScript, but there may also be a good wrapper out there that integrates with NestJS.

I created https://github.com/PublicMapping/district-builder-2/issues/54 to account for the SES specific setup.
