### ISSUE TITLE
User registration pages

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/district-builder-2#52]
AC:
* Page where user can enter email address and password to get a email with a registration link
* After submitting, the user sees a page that says "Thanks for signing up for DistrictBuilder! Please click the link in your registration email to continue."
* User can click registration link in email to confirm registration
* Email link takes user to success page that then redirects to home page

**Comment by maurizi** [comment]
We should probably update the copy in the registration email as part of this issue as well.
