### ISSUE TITLE
Containerize "manage" CLI project

### ISSUE THREAD

**Issue by kshepard** [PublicMapping/district-builder-2#66]
## Overview

We've been getting away so far without having it containerized, but it's getting to the point where we now have some additional dependencies that need to be setup (e.g. `tippecanoe`), and we'll soon need database access.

## Acceptance criteria

The "manage" CLI project is containerized and integrated with CI (e.g. code is linted and has the ability to fail a build)

**Comment by maurizi** [comment]
For accessing the database, it may be useful to use Nest in standalone mode, so we can go through TypeORM to persist data like we would normally: https://docs.nestjs.com/standalone-applications

**Comment by hectcastro** [comment]
Just wanted to throw out there that folks on the Operations team would appreciate some light pairing or the ability to participate in the review of this work.
